# Site settings
title: Social Networks and Honeybees
description: 'master thesis - documentation and findings'
url: 'http://alexa.sc/bees-sna'
baseurl: '/bees-sna/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Alexa Schlegel'
  email: hello@alexa.sc
  twitter_username: alexaschlegel
  github_username:  aschle

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
